### ISSUE TITLE
Question: Filter timings efficiently

### ISSUE THREAD

**Issue by Miggleness** [nblumhardt/serilog-timings#27]
What would be the best way to filter for logs raised by SerilogTimings?  I'm replacing my own context execution timer with SerilogTimings.  With my own roll, I can filter by the class of my timer.

I have the following code that works but wonder if there's a more efficient way.   
`.Filter.ByIncludingOnly(Matching.WithProperty("Elapsed"))`

**Comment by nblumhardt** [comment]
Howdy! Thanks for the question. The library's really designed to be a helper for generating regular events, rather than appear as a log source in its own right, so I think your method is probably about right. May be something for us to consider if/when we integrate this kind of functionality into Serilog itself, though! Thanks again.

**Comment by Miggleness** [comment]
Thanks for the rather quick response.  I'll continue using that filter then.
