### ISSUE TITLE
Microsoft.Bcl.Build dependency

### ISSUE THREAD

**Issue by tompazourek** [nblumhardt/serilog-timings#6]
Hi @nblumhardt, I noticed that when I install the NuGet package, it also asks me to install `Microsoft.Bcl.Build` package.

Could you please explain why it's needed?

I browsed through the source code briefly and couldn't find anything related.

Cheers

**Comment by nblumhardt** [comment]
Hi Tomáš,

.NET 4.5 projects that touch the new (Win8-style, now .NET Core-style) surface area often need this package in order to have System.Runtime.dll handled correctly.

I am not 100% certain why this package needs it in order to build for the net45 target, but IIRC it was the product of quite a bit of experimentation ( #4  and so-on ).

Any help removing it would be great, but we'd need to re-test from various consuming NuGet/app versions.

Cheers,
Nick

**Comment by tompazourek** [comment]
Hi Nick, thanks for clearing that out. I understand your concerns, I was thinking it was some reason like this.
